#!/bin/bash

SLEEP='/bin/sleep'

PASSWORDS='./pw'
DICTIONARY='/usr/share/dict/american-english'
#DICTIONARY='~/e20925/linux.words'

GUESSLIST=(iwantu slayer rangers charles angel flower bigdaddy rabbit wizard bigdick jasper enter rachel chris)

# audit fuction
audit()
{
	echo "Loading data"
	$SLEEP 1
	index=0
	while read p
	do
		employees[$index]="$p"
		index=`expr $index + 1`
	done <"$PASSWORDS"

	printf "\n"
	if [ ${#employees[@]} -eq 0 ];then
		echo "File is empty"
	else
		guess
		printf "\n"

		if [ ${#employees[@]} -gt 0 ];then
			dictionary
			printf "\n"
		fi
	
		if [ ${#employees[@]} -gt 0 ];then
			brute
			printf "\n"
		fi
	fi
	foundPrint
}

# Guess
guess()
{
	echo 'Guess Mode'
	$SLEEP 1
	index=0
	for guess in ${GUESSLIST[@]}
	do
		if [ ${#employees[@]} -eq 0 ]
		then
			echo 'all passwords are found'
			break
		else
			guesshash=$(echo -n "$guess" | sha256sum | awk '{print $1}')
			echo $guess
			for user in ${employees[@]}
			do
				username=$(echo $user | cut -d":" -f1)
				pwhash=$(echo $user | cut -d":" -f2)
				if [ "$guesshash" == "$pwhash" ]
				then
					employees=("${employees[@]/$user}")
					results[$index]="$username"
					index=`expr $index + 1`
					results[$index]="$guess"
					index=`expr $index + 1`
				fi
			done
		fi
	done 
}

# Dictionary Attack
dictionary()
{
	echo 'Dictionary Attack'
	$SLEEP 1
	while read guess
	do
		if [ ${#employees[@]} -eq 0 ]
		then
			echo 'all passwords are found'
			break
		else
			guesshash=$(echo -n "$guess" | sha256sum | awk '{print $1}')
			echo $guess
			for user in ${employees[@]}
			do
				username=$(echo $user | cut -d":" -f1)
				pwhash=$(echo $user | cut -d":" -f2)
				if [ "$guesshash" == "$pwhash" ]
				then
					employees=("${employees[@]/$user}")
					results[$index]="$username"
					index=`expr $index + 1`
					results[$index]="$guess"
					index=`expr $index + 1`
				fi
			done
		fi
	done <"$DICTIONARY"
}

# Brute Force
brute()
{
	echo 'Brute Force'
	$SLEEP 1
	guessarray=($(echo {a..z} {a..z}{a..z} {a..z}{a..z}{a..z} {a..z}{a..z}{a..z}{a..z}))
	start=`date +%s`
	for guess in ${guessarray[@]}
	do
		if [ ${#employees[@]} -eq 0 ]
		then
			echo all users have been found
			break
		else
			guesshash=$(echo -n "$guess" | sha256sum | awk '{print $1}')
			echo $guess
			for user in ${employees[@]}
			do
				username=$(echo $user | cut -d":" -f1)
				pwhash=$(echo $user | cut -d":" -f2)

				if [ "$guesshash" == "$pwhash" ]
				then
					employees=("${employees[@]/$user}")
					results[$index]="$username"
					index=`expr $index + 1`
					results[$index]="$guess"
					index=`expr $index + 1`
				fi
			done

			end=`date +%s`
			runtime=$((end-start))
			echo "$runtime"

			if [ $runtime -eq 120 ]
			then
				echo Time is up.
				break
			fi
		fi
	done
}

# Print out the result
foundPrint() 
{
	echo "Here is the found users\' passwords:"
	rindex=0
		
	if [ ${#results[@]} -eq 0 ]
	then
		echo 'No password found.'
	else
		for result in ${results[@]}
		do
			printf "$result"
			rindex=`expr $rindex + 1`
			check=`expr $rindex % 2`
			if [ $check -eq 0 ];then
				printf "\n"
			elif [ $check -eq 1 ];then
				printf " "
			fi
		done
	fi
}

audit




